### ISSUE TITLE
Add a readme for the project 

### ISSUE THREAD

**Issue by siddhi-244** [BugBustersCommunity/website#1]
Add guidelines on how to run the project + how to contribute + info about the project admins.

**Comment by muditchoudhary** [comment]
Hey, I would like to work on this. Can you assign it to me?

**Comment by siddhi-244** [comment]
Assigned

**Comment by muditchoudhary** [comment]
Hey, @siddhi-244 Should I create a different file [contribution-guide. md] for contribution-guideline or it should be in a single readme?

**Comment by siddhi-244** [comment]
> Hey, @siddhi-244 Should I create a different file [contribution-guide. md] for contribution-guideline or it should be in a single readme?

Different file. Will send you a link for reference

**Comment by siddhi-244** [comment]
https://github.com/siddhi-244/Embellish
