### ISSUE TITLE
Footer change

### ISSUE THREAD

**Issue by geetika001** [BugBustersCommunity/website#104]
**Is your feature request related to a problem? Please describe.**
The footer is not really impressive and seems shuffled

**Describe the solution you'd like**
I request you to allow me to change the footer.I'll make it better aligned.

Also will be sharing the screenshot once u approve me to do so.
Please assign me this issue under Hacktoberfest

**Comment by Murtaza-Farooqui** [comment]
I would like to work on this issue . Assign it to me

**Comment by goodchai0** [comment]
I have started working on it. Please , @BugBustersCommunity assign this to me under hacktoberfest 2022.
