### ISSUE TITLE
Achievement & Contact Section Navbar should be changed

### ISSUE THREAD

**Issue by ZaidKhan2002** [BugBustersCommunity/website#107]
**Describe the bug**
Navbar not Responsive
No proper navigation
Missing of logo.

**To Reproduce**
1. Go to 'Website'
2. Click on '.Achievement & Contact us'
3. See error

**Expected behavior**
Navbar should be responsive and proper navigation should be added. 

**Screenshots**
<img width="1440" alt="Screenshot 2022-10-09 at 6 23 43 PM" src="https://user-images.githubusercontent.com/71960989/194758064-b381948b-a860-461f-b56a-bace24e24697.png">

<img width="1440" alt="Screenshot 2022-10-09 at 6 23 55 PM" src="https://user-images.githubusercontent.com/71960989/194758069-7081733c-f137-47c6-b356-37670865685f.png">

**Comment by Bhushan0246** [comment]
Hi
I want to work on this issue can you please assign me.

**Comment by ZaidKhan2002** [comment]
Should I start working on this ? @siddhi-244 @Aditi-Singh16

**Comment by siddhi-244** [comment]
Sure @ZaidKhan2002

**Comment by ZaidKhan2002** [comment]
Someone resolved this issue ...
