### ISSUE TITLE
Add A customized scroller

### ISSUE THREAD

**Issue by rahul-aggarwal000005** [BugBustersCommunity/website#108]
**Is your feature request related to a problem? Please describe.**
This feature helps to change the regular scrollar that is by default by the browser.

**Describe the solution you'd like**
We can use the -webkit-scrollbar-track to change the scrollbar

**Describe alternatives you've considered**
Use any external library to make it more attractive.

**Comment by goodchai0** [comment]
I want to work on it. Please , https://github.com/BugBustersCommunity assign this to me under hacktoberfest 2022.
