### ISSUE TITLE
Improve the footer

### ISSUE THREAD

**Issue by AditiSingh2003** [BugBustersCommunity/website#116]
**Describe the bug**
To improve the display of footer 

**Expected behavior**
Will increase the outlook of the website

**Screenshots**
![Screenshot (39)](https://user-images.githubusercontent.com/97729662/196019845-9127841e-a057-411d-ba43-97c44d44d768.png)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome

**Additional context**

**Comment by ashish5433** [comment]
hey @AditiSingh2003 can you assign this to me
