### ISSUE TITLE
Applying the Hover effect

### ISSUE THREAD

**Issue by AditiSingh2003** [BugBustersCommunity/website#117]
**Describe the bug**
When we put the cursor on the cards it does not display the hover effect.

**Expected behavior**
Hover and transition effect on cards.

**Screenshots**
![Screenshot (40)](https://user-images.githubusercontent.com/97729662/196019951-1cd4b397-8fd1-426a-94fb-9ca7e5ec66af.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by ashish5433** [comment]
hey @AditiSingh2003 can you assign this to me

**Comment by chaudhary-99** [comment]
hii @siddhi-244 can you pls assign this work to me
