### ISSUE TITLE
The site is not responsive

### ISSUE THREAD

**Issue by AditiSingh2003** [BugBustersCommunity/website#118]
**Describe the bug**
when we look for responsiveness the site is not responsive.

**Expected behavior**
Responsive when reduced

**Screenshots**
![Screenshot (41)](https://user-images.githubusercontent.com/97729662/196020025-bcc90c52-446b-40a4-bd26-bf3609f54f8a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by chaudhary-99** [comment]
hii @siddhi-244 can you pls assign this work to me
