### ISSUE TITLE
Improve footer of the website in mobile view!

### ISSUE THREAD

**Issue by siddhi-244** [BugBustersCommunity/website#16]
**Is your feature request related to a problem? Please describe.**
Improve footer of the website in mobile view!

**Comment by vikas-kmr1** [comment]
@siddhi-244 assign this to me please.

**Comment by Akanksha-Sen** [comment]
Please assign me this issue.

**Comment by siddhi-244** [comment]
> @siddhi-244 assign this to me please.

Assigning it to you !

**Comment by vikas-kmr1** [comment]
@siddhi-244  issue level?

**Comment by siddhi-244** [comment]
> @siddhi-244 issue level?

That would be given according to your code quality once your pr is made

**Comment by vikas-kmr1** [comment]
@siddhi-244  sorry busy with other tasks, assign someone else.

**Comment by SumitKanth** [comment]
@siddhi-244 Can you assign me

**Comment by siddhi-244** [comment]
> @siddhi-244 Can you assign me

Sure🔥🔥

**Comment by siddhi-244** [comment]
This issue is still open folks👀
