### ISSUE TITLE
Want to create hover effect on social icon buttons

### ISSUE THREAD

**Issue by muditchoudhary** [BugBustersCommunity/website#17]
**Is your feature request related to a problem? Please describe.**
There is no hover effect on social icon buttons. which don't look good and users may get confused if they are clickable.

**Describe the solution you'd like**
I want to add a hover effect on the buttons.

**Describe alternatives you've considered**
I don't have an alternative suggestion for this.

**Additional context**

![Peek 2022-07-23 08-26](https://user-images.githubusercontent.com/74391865/180588142-b64a2d52-71b1-4097-9f25-92fb1bab9adc.gif)

Can you assign it to me?

**Comment by siddhi-244** [comment]
Assigning it to you🥳🥳
