### ISSUE TITLE
Want to add a contact section

### ISSUE THREAD

**Issue by vedsom** [BugBustersCommunity/website#18]
**Is your feature request related to a problem? Please describe.** 

There is no proper and direct communication channel between site owner and user
**Describe the solution you'd like**

A want to add a good contact page with great css styles which will really helpful to user.

**Comment by vedsom** [comment]
@Aditi-Singh16 can you assign me this issue?

**Comment by siddhi-244** [comment]
Assigning it to you 🥳🥳
