### ISSUE TITLE
Add pr and issue template 

### ISSUE THREAD

**Issue by siddhi-244** [BugBustersCommunity/website#2]
Add pull request and issue template. You can take reference from here (https://github.com/siddhi-244/Embellish/tree/main/.github/ISSUE_TEMPLATE)
(https://github.com/siddhi-244/Embellish/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by afreenabegum** [comment]
please do assign it to me!

**Comment by siddhi-244** [comment]
Assigned

**Comment by afreenabegum** [comment]
@siddhi-244 , where we need to add pr and issue template files (In which directory) ?

**Comment by siddhi-244** [comment]
I have given the reference.  You have to do the same

**Comment by afreenabegum** [comment]
> I have given the reference. You have to do the same

Do I need to  add exact same content overthere?
For pull request file, I should also add other files like contributing guidelines?

**Comment by siddhi-244** [comment]
> > I have given the reference. You have to do the same
> 
> Do I need to add exact same content overthere? For pull request file, I should also add other files like contributing guidelines?

You can. Just change a few things in reference to bug busters !

**Comment by afreenabegum** [comment]
> > > I have given the reference. You have to do the same
> > 
> > 
> > Do I need to add exact same content overthere? For pull request file, I should also add other files like contributing guidelines?
> 
> You can. Just change a few things in reference to bug busters !

**Comment by siddhi-244** [comment]
Don't add link for now. As that file is not created !
