### ISSUE TITLE
Improve navbar of the website

### ISSUE THREAD

**Issue by tanya-gupta25** [BugBustersCommunity/website#20]
- Will increase the size of logo in navbar 
- will shift all the navbar headings to the right side of navbar with hover effects

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSOC

**Comment by siddhi-244** [comment]
Please add description to your issue

**Comment by tanya-gupta25** [comment]
> Please add description to your issue

done

**Comment by siddhi-244** [comment]
> > Please add description to your issue
> 
> done

Assigning it to you🥳🥳
