### ISSUE TITLE
Add photos in cards and social media links 

### ISSUE THREAD

**Issue by tanya-gupta25** [BugBustersCommunity/website#21]
- Will add photos of the members in the cards
- will add social media links (twitter, insta, github, linkedin) of the members in the cards

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSOC

**Comment by siddhi-244** [comment]
Please add description to your issu3

**Comment by tanya-gupta25** [comment]
> Please add description to your issu3

done

**Comment by siddhi-244** [comment]
Assigning it to you🥳🥳🥳

**Comment by siddhi-244** [comment]
Next time please follow issue template

**Comment by tanya-gupta25** [comment]
> Next time please follow issue template

For sure, sorry for this time.
Kindly provide me all the social media links and the photos of the members so I can add them

**Comment by siddhi-244** [comment]
> > Next time please follow issue template
> 
> For sure, sorry for this time. Kindly provide me all the social media links and the photos of the member so I can add them

Cool. Will give you social media links on discord and photo you can take from LinkedIn itself

**Comment by Soumya-Kushwaha** [comment]
If there's anything left in this, I would like to work on it please

**Comment by tanya-gupta25** [comment]
Hey, actually I am working on it ,but waiting for the PA to give me photos and social links of members

**Comment by Soumya-Kushwaha** [comment]
Cool. All the best!
