### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by SumitKanth** [BugBustersCommunity/website#22]
Want to work on navbar, can you assign me 
I will contribute under HCSOC22'

**Comment by siddhi-244** [comment]
Describe about the issue

**Comment by SumitKanth** [comment]
# About the issue
1. Navbar's logo size is to small.
2. Navbar links the not styled .
3. Navbar height not like the average height of navbar.
4. In html files the css is used in inline style witch is not the better way to right css.
5. And some other changes I will see while working on it.

**Comment by siddhi-244** [comment]
Assigned

**Comment by SumitKanth** [comment]
thanks
