### ISSUE TITLE
Add contributors section

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [BugBustersCommunity/website#25]
**Is your feature request related to a problem? Please describe.**
This would feature all the contributors on the readme

**Describe the solution you'd like**
All the contributors will be displayed as "Project Contributors" on main readme

**Additional context**
No additional context

**Comment by siddhi-244** [comment]
Describe your issue. Follow the template.

**Comment by Soumya-Kushwaha** [comment]
Edited

**Comment by siddhi-244** [comment]
Go on🥳
