### ISSUE TITLE
Improve the navbar in mobile view !

### ISSUE THREAD

**Issue by siddhi-244** [BugBustersCommunity/website#3]
![Screenshot_20220715-090041_Chrome](https://user-images.githubusercontent.com/69195262/179144767-286fb4ef-44de-4495-87b9-5585d6569841.jpg)

Improve this !

**Comment by akashrchandran** [comment]
Please assign me this😁.

**Comment by siddhi-244** [comment]
Go on🥳🎊

**Comment by siddhi-244** [comment]
Any updates?
