### ISSUE TITLE
Fix navbar & its responsiveness

### ISSUE THREAD

**Issue by tanya-gupta25** [BugBustersCommunity/website#31]
**Expected behavior**
- will shift the elements of navbar to right
- will add the name of the website 
- will make navbar responsive
- implement toggle button for navbar

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSOC

**Comment by siddhi-244** [comment]
Assigning it to you

**Comment by tanya-gupta25** [comment]
@siddhi-244 Hey, Can I use Bootstrap for the navbar? I can try kind of animated navbar

**Comment by Aditi-Singh16** [comment]
Hi @tanya-gupta25 , sure bootstrap is always better
also what kind of animations will you be trying?
