### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by SumitKanth** [BugBustersCommunity/website#32]
Want to add a favicon to the website
Will contribute under HSOC22

**Comment by siddhi-244** [comment]
> Want to add a favicon to the website Will contribute under HSOC22

Can uh describe the issue more ?

**Comment by SumitKanth** [comment]
Without favcion the website looks dull, so I want to add favicon and the favicon will we type of bug img.

**Comment by siddhi-244** [comment]
> Without favcion the website looks dull, so I want to add favicon and the favicon will we type of bug img.

Please share an ss. I am still unclear about it

**Comment by SumitKanth** [comment]
![Screenshot (278)](https://user-images.githubusercontent.com/90907720/181271960-dcd87033-37e7-4217-97e2-90b82ce34a84.png)
Favicon is not their

**Comment by siddhi-244** [comment]
> ![Screenshot (278)](https://user-images.githubusercontent.com/90907720/181271960-dcd87033-37e7-4217-97e2-90b82ce34a84.png) Favicon is not their

We don't need it

**Comment by Aditi-Singh16** [comment]
Hi! @siddhi-244 @SumitKanth I think having favicon would be good
I think its always better to have the bugbusters logo besides the title

**Comment by Aditi-Singh16** [comment]
@siddhi-244 what do you think

**Comment by siddhi-244** [comment]
> @siddhi-244 what do you think

Cool. Let's do this @SumitKanth

**Comment by SumitKanth** [comment]
@siddhi-244 @Aditi-Singh16 thanks, I will do this

**Comment by SumitKanth** [comment]
@siddhi-244 why you have not closed this issue
