### ISSUE TITLE
Want to improve the accessibility of the website

### ISSUE THREAD

**Issue by muditchoudhary** [BugBustersCommunity/website#34]
**Is your feature request related to a problem? Please describe.**
The website is not fully accessible which may create problems for some of the users on the internet. Like some images don't have alt text, skip heading level, etc.

**Describe the solution you'd like**
I want to improve the accessibility of the website. I will fix the heading levels, Contrast issues or add alt text wherever needed, etc.

**Describe alternatives you've considered**
Don't have an alternative solution for this issues

**Additional context**
![image](https://user-images.githubusercontent.com/74391865/181245031-da7b5b38-5de7-4a4d-b7e3-9890136d69e0.png)

**Comment by siddhi-244** [comment]
Assigning it to you

**Comment by Aditi-Singh16** [comment]
Thats a good find!
