### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Akanksha-Sen** [BugBustersCommunity/website#38]
**Is your feature request related to a problem? Please describe.**
Footer

**Describe the solution you'd like**
Want to improve footer and also would add effects to SUBMIT button.

**Comment by siddhi-244** [comment]
Assigning it to you🥳

**Comment by vedsom** [comment]
@siddhi-244 can you give me this issue too. It is minor issue I will complete parallel with achievement section

**Comment by siddhi-244** [comment]
Sure!
