### ISSUE TITLE
Achievements tab in navbar

### ISSUE THREAD

**Issue by Aditi-Singh16** [BugBustersCommunity/website#42]
**Describe the solution you'd like**
Add all achievements, webinars and workshops conducted by bugbusters till now
take reference from here -  [BugBusters YT](https://www.youtube.com/channel/UCqH6JeCTHngoGjV-5VlKNHg)

**Comment by SumitKanth** [comment]
@Aditi-Singh16 can you describe the issue, like how we should add and what we should add ?

**Comment by siddhi-244** [comment]
> @Aditi-Singh16 can you describe the issue, like how we should add and what we should add ?

You can add our latest sessions which are on youtube. Basically embedding youtube videos and make a new page called achievements.html and link it with navbar on home page

**Comment by vedsom** [comment]
> > @Aditi-Singh16 can you describe the issue, like how we should add and what we should add ?
> 
> You can add our latest sessions which are on youtube. Basically embedding youtube videos and make a new page called achievements.html and link it with navbar on home page

@siddhi-244 @Aditi-Singh16 can I work on it?

**Comment by siddhi-244** [comment]
> > > @Aditi-Singh16 can you describe the issue, like how we should add and what we should add ?
> > 
> > 
> > You can add our latest sessions which are on youtube. Basically embedding youtube videos and make a new page called achievements.html and link it with navbar on home page
> 
> @siddhi-244 @Aditi-Singh16 can I work on it?

You can. But the hsoc has ended already.  Like it will end at 11 59

**Comment by vedsom** [comment]
> > > > @Aditi-Singh16 can you describe the issue, like how we should add and what we should add ?
> > > 
> > > 
> > > You can add our latest sessions which are on youtube. Basically embedding youtube videos and make a new page called achievements.html and link it with navbar on home page
> > 
> > 
> > @siddhi-244 @Aditi-Singh16 can I work on it?
> 
> You can. But the hsoc has ended already. Like it will end at 11 59

I will do it no worries. YouTube link consist only 3 videos I have to add that's 3 right?

**Comment by siddhi-244** [comment]
Right

**Comment by vedsom** [comment]
> Right

@siddhi-244 whenever you get time. Please update me.

**Comment by vedsom** [comment]
@siddhi-244 will it count or not?

**Comment by siddhi-244** [comment]
It won't. I already told you that

**Comment by vedsom** [comment]
> 

If there is anyway, please count it.

**Comment by siddhi-244** [comment]
If we do it for you , Then we have to do it for others too.

**Comment by vedsom** [comment]
Ok
