### ISSUE TITLE
Contact Page Enhancement and Styling

### ISSUE THREAD

**Issue by SahilAnower** [BugBustersCommunity/website#46]
**🐛BUG**
On clicking the submit button, not showing whether form has been submitted or not. Also, whether it is actually submitting don't know either. Also resetting of form-fields should be there, and user should get redirected to homepage. Validation can also be provided to the same before submitting.

**Contact Page ->Submit**

Also Making UI look attractive another feature.

**Comment by SahilAnower** [comment]
Assign me to this!

**Comment by siddhi-244** [comment]
Sure
