### ISSUE TITLE
Add dark mode toggle

### ISSUE THREAD

**Issue by sudhanshu-p** [BugBustersCommunity/website#47]
I mean... come on, dark mode is like the most loved thing by developers, who does not like dark mode? I think I can help this website get a dark mode. I would love to work on this issue!

**Comment by siddhi-244** [comment]
> I mean... come on, dark mode is like the most loved thing by developers, who does not like dark mode? I think I can help this website get a dark mode. I would love to work on this issue!

Sure !

**Comment by krishnabiradar310802** [comment]
@siddhi-244 can you assign me this issue?

**Comment by Vishrut19** [comment]
Hey! Can I get this issue ?? @sudhanshu-p
