### ISSUE TITLE
Improve Footer UI

### ISSUE THREAD

**Issue by namn-grg** [BugBustersCommunity/website#48]
**Is your feature request related to a problem? Please describe.**
The footer is really sick. The format of the footer is not eye-pleasing. Also, a small bug where copywriter is written is not coloured.

**Describe the solution you'd like**
Would like to change the UI of footer and correct the small bug.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/97289118/192879589-ed9f5e8f-1845-4a26-98bf-43cba22fd37a.png)

**Comment by namn-grg** [comment]
Hello, can you please assign me this issue?

**Comment by siddhi-244** [comment]
Sure

**Comment by dhrumishah** [comment]
If this is still open, can I work on this?

**Comment by namn-grg** [comment]
> If this is still open, can I work on this?

Hi Dhrumi, go ahead. I might take more time as I am a little occupied. Please assign her.

**Comment by dhrumishah** [comment]
hey @siddhi-244 , Can you please assign me?

**Comment by siddhi-244** [comment]
> hey @siddhi-244 , Can you please assign me?

Sure
