### ISSUE TITLE
Improve navbar UI

### ISSUE THREAD

**Issue by PritamSarbajna** [BugBustersCommunity/website#49]
The navbar links are not visible when hovering.

https://user-images.githubusercontent.com/90236635/192940137-9fe5e5b5-1000-4c24-a322-71c5125f7b0d.mp4

Happy to get assigned and work on

**Comment by siddhi-244** [comment]
Sure🙌

**Comment by PritamSarbajna** [comment]
Thank you so much @siddhi-244. Is this repo up for hacktoberfest '22 ??

**Comment by siddhi-244** [comment]
> Thank you so much @siddhi-244. Is this repo up for hacktoberfest '22 ??

Yes it is !

**Comment by PritamSarbajna** [comment]
@siddhi-244 Thanks 🚀

**Comment by dhrumishah** [comment]
Is this issue still open? I would like to work on this issue.
