### ISSUE TITLE
Fix grammar and enhance readability

### ISSUE THREAD

**Issue by ashmeet-ashmeet** [BugBustersCommunity/website#5]
1. Fix the incorrect articles (there's "an Java" written on a card)
1. Put capital alphabets wherever required. They're missing at some places, for instance "working at google"
1. Enhance readability by putting necessary spaces between commas and the words after it. So, "events,hackathons,internships" will look like "events, hackathons, internships"

**Comment by siddhi-244** [comment]
I have assigned an issue to you about Loren ipsum. You can cover this part over there!
