### ISSUE TITLE
Improve the Achievements page

### ISSUE THREAD

**Issue by nown1ne** [BugBustersCommunity/website#51]
## Weird white border around the page 
![image](https://user-images.githubusercontent.com/25835195/193399221-04f243c9-9391-43a8-be96-073294194bbc.png)

## The li element style is shown at the bottom
![image](https://user-images.githubusercontent.com/25835195/193399258-2aeac8f0-f9bf-4fa7-82f7-541ef5e85d51.png)

## The video titles are evenly spread out (bringing the title closer to the video would be better)
![image](https://user-images.githubusercontent.com/25835195/193399309-3e03c3cd-b2be-4edd-8692-251b83d219eb.png)

## Page is not responsive
![image](https://user-images.githubusercontent.com/25835195/193399351-1d7db19c-c4ef-4d3d-809a-5dea07bf79a9.png)

Would be really happy to work on these issues and start my hacktoberfest/open source journey.
Please assign the issue to me.

**Comment by siddhi-244** [comment]
> ## Weird white border around the page
> ![image](https://user-images.githubusercontent.com/25835195/193399221-04f243c9-9391-43a8-be96-073294194bbc.png)
> 
> ## The li element style is shown at the bottom
> ![image](https://user-images.githubusercontent.com/25835195/193399258-2aeac8f0-f9bf-4fa7-82f7-541ef5e85d51.png)
> 
> ## The video titles are evenly spread out (bringing the title closer to the video would be better)
> ![image](https://user-images.githubusercontent.com/25835195/193399309-3e03c3cd-b2be-4edd-8692-251b83d219eb.png)
> 
> ## Page is not responsive
> ![image](https://user-images.githubusercontent.com/25835195/193399351-1d7db19c-c4ef-4d3d-809a-5dea07bf79a9.png)
> 
> Would be really happy to work on these issues and start my hacktoberfest/open source journey. Please assign the issue to me.

Sure!
