### ISSUE TITLE
Center items on the home page

### ISSUE THREAD

**Issue by nown1ne** [BugBustersCommunity/website#53]
## The headings/titles are not centered
![image](https://user-images.githubusercontent.com/25835195/193403811-06d2e029-f1d7-4392-b84d-28940ba26b75.png)

## The image under this section is not centered
![image](https://user-images.githubusercontent.com/25835195/193403843-f6f329bf-f3ae-446d-a594-d307904d169a.png)

## Other images in the homepage can also be centered to make the page fill up more screen and match with the content
![image](https://user-images.githubusercontent.com/25835195/193403902-42953e61-4558-458a-af87-9066d12679ee.png)

**Comment by nown1ne** [comment]
Please assign this issue to me

**Comment by nown1ne** [comment]
@siddhi-244 Any updates on this issue ??

**Comment by siddhi-244** [comment]
Assigning it to you🥳
