### ISSUE TITLE
Profile icon 

### ISSUE THREAD

**Issue by Harsh3363** [BugBustersCommunity/website#54]
**Describe the bug**
In profile section the icons are not loading properly 
**To Reproduce**

**Expected behavior**
Relevant icons or images should be shown 

**Screenshots**

![bug](https://user-images.githubusercontent.com/72756692/193404284-1d94e152-c098-49f3-bbd4-fa236437dae6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Harsh3363** [comment]
Hii @siddhi-244 please assign this to me

**Comment by siddhi-244** [comment]
> Hii @siddhi-244 please assign this to me

I think it's not a bug. But there are no images.  You can search these people on linkedin and then add their pictures !

**Comment by Harsh3363** [comment]
> > Hii @siddhi-244 please assign this to me
> 
> I think it's not a bug. But there are no images. You can search these people on linkedin and then add their pictures !

sure I will do that
