### ISSUE TITLE
Remove the duplicate element in the footer

### ISSUE THREAD

**Issue by Harsh3363** [BugBustersCommunity/website#55]
**Describe the bug**
The social media icons are placed twice which I want to fix and to add a hover effect for a better user experience

**To Reproduce**

**Expected behavior**

**Screenshots**
![bug1](https://user-images.githubusercontent.com/72756692/193404774-fb9c4bc2-3b46-402e-a4cb-67e1abbea2fc.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Harsh3363** [comment]
@siddhi-244 please assign this to me

**Comment by siddhi-244** [comment]
Sure !
