### ISSUE TITLE
Page for Link section

### ISSUE THREAD

**Issue by Harsh3363** [BugBustersCommunity/website#62]
**Is your feature request related to a problem? Please describe.**
Currrently the Link button on navbar is not pointing any page it will be good if there is one separate page for that

**Describe the solution you'd like**
I would like to add a Link page having some articles and resources for getting started with different tech stacks

**Describe alternatives you've considered**

**Additional context**

![enh1](https://user-images.githubusercontent.com/72756692/193422989-256b74ea-c6be-4af9-b454-3890826bf721.png)

**Comment by Harsh3363** [comment]
@siddhi-244 please assign this to me I would like to work on this

**Comment by siddhi-244** [comment]
> @siddhi-244 please assign this to me I would like to work on this

We need to remove the link section.

**Comment by Harsh3363** [comment]
> > @siddhi-244 please assign this to me I would like to work on this
> 
> We need to remove the link section. 

Can I do that?

**Comment by siddhi-244** [comment]
> > > @siddhi-244 please assign this to me I would like to work on this
> > 
> > 
> > We need to remove the link section.
> 
> Can I do that?

That's too basic. You can resolve some other issue along with this !

**Comment by Harsh3363** [comment]
> > > > @siddhi-244 please assign this to me I would like to work on this
> > > 
> > > 
> > > We need to remove the link section.
> > 
> > Can I do that?
> 
> That's too basic. You can resolve some other issue along with this !

Sure

**Comment by kasib12** [comment]
Hey @siddhi-244 . I want to help you in resolving this issue. Please assign it to me and answer a few questions that I have regarding the link section.
