### ISSUE TITLE
Mismatch in the name of main branch (docs)

### ISSUE THREAD

**Issue by nown1ne** [BugBustersCommunity/website#64]
## The primary branch of the project is **Master** but in the readme it is referred to as _main_

It causes the following problem 
![image](https://user-images.githubusercontent.com/25835195/193424785-e7972857-e03e-4de4-b268-72ea9d9290ab.png)

**Comment by nown1ne** [comment]
@siddhi-244  Please assign this issue to me

**Comment by siddhi-244** [comment]
> @siddhi-244 Please assign this issue to me

Thanks for pointing that out but it would be great if you can solve one more issue with this as this issue won't have that weightage!

**Comment by nown1ne** [comment]
ok understood

**Comment by siddhi-244** [comment]
Closing it as it's resolved
