### ISSUE TITLE
Adding Animation

### ISSUE THREAD

**Issue by alisamadiii** [BugBustersCommunity/website#66]
**Is your feature request related to a problem? Please describe.**
No, It's gonna be a new Feature.

**Describe the solution you'd like**
I just want to add animation when user is scrolling.

**Describe alternatives you've considered**
I'll gsap Library for this issue.

**Additional context**

**Comment by siddhi-244** [comment]
No for now we don't need it. We are more focused on making the website responsive and solving all the bugs

**Comment by alisamadiii** [comment]
But it will look amazing if you have animations.
I've made a PR, so You can check the website.

**Comment by siddhi-244** [comment]
> But it will look amazing if you have animations. I've made a PR, so You can check the website.

Ok let me see what type of animation is added !

**Comment by siddhi-244** [comment]
Will check your pr!

**Comment by alisamadiii** [comment]
Thank You
