### ISSUE TITLE
Readme upadte #hacktoberfest

### ISSUE THREAD

**Issue by Spyder15** [BugBustersCommunity/website#73]
we can add hacktoberfest'22 , section also in readme , where user or developer or beginner can come and see that this repo is part of hacktoberfest'22 with some image too , so user can fork this repo and make some PR..

**Comment by Spyder15** [comment]
@siddhi-244 You can assign me to do this part.

**Comment by siddhi-244** [comment]
Nope thats currently not needed. We have added the Hacktoberfest topic
