### ISSUE TITLE
Add a confirmation popup

### ISSUE THREAD

**Issue by sumeetk10** [BugBustersCommunity/website#76]
**Is your feature request related to a problem? Please describe.**
No, I would like to add a popup message stating submitted successful. Also I would like to align the footer properly.

**Describe the solution you'd like**
Upon clicking the submit button in Contact Us page, a popup will appear which gives the confirmation.

**Describe alternatives you've considered**
In home page footer section submit button should be rename with subscribe as I am subscribing the newsletter along with this it should also show confimation popup.

**Additional context**
![Screenshot 2022-10-03 170617](https://user-images.githubusercontent.com/81513463/193570596-fee63ac8-c030-47db-9502-1a514bbff154.png)

**Comment by sumeetk10** [comment]
Hey @siddhi-244 please assign this issue.

**Comment by siddhi-244** [comment]
We don't need a popup
