### ISSUE TITLE
Improving UI when links in navigation bar are hovered 

### ISSUE THREAD

**Issue by hardik-pratap-singh** [BugBustersCommunity/website#77]
May I improve the ui when links are hovered on navigation bar.
Can I take this issue ?

**Comment by siddhi-244** [comment]
> May I improve the ui when links are hovered on navigation bar. Can I take this issue ?

I didn't get your issue

**Comment by hardik-pratap-singh** [comment]
When you actually go on the elements of the navigation bar it transits
showing white color which I think can be improved in order to look more
attractive!

**Comment by goodchai0** [comment]
I want to work on it. Please , https://github.com/BugBustersCommunity assign this to me under hacktoberfest 2022.
