### ISSUE TITLE
Improve the scroll bar

### ISSUE THREAD

**Issue by Arbtrage** [BugBustersCommunity/website#78]
**Is your feature request related to a problem? Please describe.**
The scroll bar is really basic and would surely look better if it was customized.

**Describe the solution you'd like**
Would like to change the scrollbar to a custom one to match the overall vibe of the website.

**Describe alternatives you've considered**
None

**Additional context**
![pic](https://user-images.githubusercontent.com/100552235/193736064-4e1cbf50-62eb-4e4c-8bb6-215dbedb2f6d.jpeg)

**Comment by Arbtrage** [comment]
Hello @siddhi-244  , can you please assign me this issue, I would really like to work on it and make the website look better.

**Comment by siddhi-244** [comment]
Sure!
