### ISSUE TITLE
Make the website responsive 

### ISSUE THREAD

**Issue by siddhi-244** [BugBustersCommunity/website#8]
Make the website compatible on all devices !

**Comment by YashDaga17** [comment]
Can I try ?

**Comment by ashmeet-ashmeet** [comment]
I'd like to work on this.

**Comment by YashDaga17** [comment]
> 

I'd like to work on this one.

**Comment by siddhi-244** [comment]
> I'd like to work on this.

Assigning it to you. 
You have 3 days to complete this issue.

**Comment by siddhi-244** [comment]
> > 
> 
> I'd like to work on this one.

Assigning it to you !

**Comment by siddhi-244** [comment]
@ashmeet-chhabra you have to inform us before removing the assignment

**Comment by ashmeet-ashmeet** [comment]
> @ashmeet-chhabra you have to inform us before removing the assignment

my apologies. didn't know that was a thing

**Comment by siddhi-244** [comment]
@YashDaga17 any updates?

**Comment by YashDaga17** [comment]
I don't think I can do it in 3 days maybe you can assign it to the others

**Comment by siddhi-244** [comment]
> I don't think I can do it in 3 days maybe you can assign it to the others

Cool. There is no other request now. So you have time. If you are unable to do it. Lemme know

**Comment by vedsom** [comment]
@siddhi-244 can you explain a little about what you exactly want in site? I want to work on this part.

**Comment by siddhi-244** [comment]
> @siddhi-244 can you explain a little about what you exactly want in site? I want to work on this part.

The website is not responsive on mobile devices,  you have to make it compatible on mobile devices

**Comment by vedsom** [comment]
> > @siddhi-244 can you explain a little about what you exactly want in site? I want to work on this part.
> 
> The website is not responsive on mobile devices, you have to make it compatible on mobile devices

 @siddhi-244  Can you assign me this issue!!

**Comment by siddhi-244** [comment]
> > > @siddhi-244 can you explain a little about what you exactly want in site? I want to work on this part.
> > 
> > 
> > The website is not responsive on mobile devices, you have to make it compatible on mobile devices
> 
> @siddhi-244 Can you assign me this issue!!

Sure

**Comment by siddhi-244** [comment]
Any updates on this?

**Comment by vedsom** [comment]
> Any updates on this?

Yaa, actually currently my end sem are going on and they are back to back, just give me 2 days more I will come up with solution

**Comment by siddhi-244** [comment]
Sure. All the very besttt
