### ISSUE TITLE
Adding timeline in the achievements page

### ISSUE THREAD

**Issue by amitp138** [BugBustersCommunity/website#81]
**Is your feature request related to a problem? Please describe.**
In the achievements page it has very simple ui and also there is no mention of date and time of the achievements 

**Describe the solution you'd like**
Instead of showing simply videos we can make a timeline of those video and show according to their timeline
![image](https://user-images.githubusercontent.com/86116926/193766783-3dd90275-49e5-4d06-90e3-b0461d9edbc8.png)
we can do like the above image it would more attractive after doing this
**Describe alternatives you've considered**

**Additional context**

**Comment by siddhi-244** [comment]
Timeline isn't needed. If you can improve the achievement page in other way then I can assign it to you

**Comment by amitp138** [comment]
yes I can change the ui of the achievements page

**Comment by amitp138** [comment]
and also can i change the ui of  contact us page

**Comment by siddhi-244** [comment]
Sure!

**Comment by amitp138** [comment]
thank you so much

**Comment by amitp138** [comment]
Ma'am the pr has been merged but can you also add the hactoberfest tag please in this issue because it is still not counted in my profile of hactoberfest it shows pending

**Comment by amitp138** [comment]
Pr #106
