### ISSUE TITLE
Sticky Navbar 

### ISSUE THREAD

**Issue by ZaidKhan2002** [BugBustersCommunity/website#83]
**Describe the bug**
Navbar supposed to be sticked at top when scrolling down for better navigation

**To Reproduce**
1. Go to website
2. Scroll down 
3. See error

**Expected behavior**
Navbar should be fixed at top.

**Screenshots**

**Comment by siddhi-244** [comment]
Sure

**Comment by ZaidKhan2002** [comment]
Hey @siddhi-244 I made the desired changes but my PR got closed.. Kindly look into this
