### ISSUE TITLE
Improving design and UI of nav bar. Increase and change the font size and family of texts

### ISSUE THREAD

**Issue by ShivamAgarwal-code** [BugBustersCommunity/website#84]
Assign me this issue..

**Comment by ShivamAgarwal-code** [comment]
Also put the Hactoberfest'22 label

**Comment by siddhi-244** [comment]
Can you explain it more precisely?

**Comment by ShivamAgarwal-code** [comment]
**Is your feature request related to a problem? Please describe.**
Not good font size of the texts in navbar, light colors on hovering over it, not good UI design or background color

**Describe the solution you'd like**
I want to look the navbar better than existing thus changing and adding some CSS designs on it..

**Describe alternatives you've considered**
I tried to change the font family and size of navbar texts, changed the color of the navbar on hover, changed the background color and also the box-shadow..

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** Not good font size of the texts in navbar, light colors on hovering over it, not good UI design or background color
> 
> **Describe the solution you'd like** I want to look the navbar better than existing thus changing and adding some CSS designs on it..
> 
> **Describe alternatives you've considered** I tried to change the font family and size of navbar texts, changed the color of the navbar on hover, changed the background color and also the box-shadow..

Instead work on the navbar for mobile view !
