### ISSUE TITLE
Modify the contact us page

### ISSUE THREAD

**Issue by Arbtrage** [BugBustersCommunity/website#85]
**Is your feature request related to a problem? Please describe.**
The contact page is really basic and is not that much appealing to the eyes.

**Describe the solution you'd like**
Would like to create a better contact us page .

**Describe alternatives you've considered**
None

**Additional context**
![Newissue](https://user-images.githubusercontent.com/100552235/193794628-acb9dc63-a369-4382-88df-c83600d4908d.jpeg)

**Comment by Arbtrage** [comment]
Hello @siddhi-244 ,can you please assign me this issue, I would like to work on it.

**Comment by siddhi-244** [comment]
> Hello @siddhi-244 ,can you please assign me this issue, I would like to work on it.

Sure

**Comment by krishnabiradar310802** [comment]
Hello @siddhi-244 can you assign me this issue?

**Comment by tanishk-23** [comment]
@siddhi-244 can you assign this issue to me?

**Comment by SahilAnower** [comment]
Close this pull request and issue, as it is resolved now through #90. @siddhi-244 , and also please change the gmail here from "youremail@gmail.com" to your personal or bugbusters official email address, if possible. Thank You!

![bugbusters](https://user-images.githubusercontent.com/49086583/194259889-a659278b-e296-4bcb-8b4f-58e82a943e85.jpg)

> Also please do tell me whether to make a backend for our website? We can raise it as a isssue, or maybe work ourselves.
