### ISSUE TITLE
Font style of headings

### ISSUE THREAD

**Issue by darshikaguptaa** [BugBustersCommunity/website#88]
Headings are looking very plain and simple

Fixing the alignment and using a better font size of the headings such as about etc.

**Comment by Ayush7614** [comment]
Go Ahead @darshikaguptaa

**Comment by darshikaguptaa** [comment]
Thanks
Can you please label it as hacktoberfest also

**Comment by Ayush7614** [comment]
> Thanks Can you please label it as hacktoberfest also

@siddhi-244 please look in to this

**Comment by siddhi-244** [comment]
Sure!
